{% set name = "lifelib" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/lifelib-{{ version }}.tar.gz
  sha256: af12a3e053e9f1b4eea3723b7362d6d3b3fb3c783a45dcb3503604905ad43672

build:
  entry_points:
    - lifelib-create = lifelib.commands.create:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - modelx >=0.12.1
    - python >={{ python_min }}

test:
  imports:
    - lifelib
  commands:
    - pip check
    - lifelib-create --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://lifelib.io
  summary: Actuarial models in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
