{% set name = "lifelib" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/lifelib-{{ version }}.tar.gz
  sha256: d69f0a838c3d1eab0e0221da21554b058d03669017619448391f7f25bb14b70e

build:
  entry_points:
    - lifelib-create = lifelib.commands.create:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - modelx >=0.12.1
    - python >={{ python_min }}

test:
  imports:
    - lifelib
  commands:
    - pip check
    - lifelib-create --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://lifelib.io
  summary: Actuarial models in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
