{% set name = "lifelib" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lifelib-{{ version }}.tar.gz
  sha256: 53d04a0730c2f78a866c22708ee02914914a42652588e9b5cee669257b0123c6

build:
  entry_points:
    - lifelib-create = lifelib.commands.create:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - modelx >=0.12.1
    - python >=3.6

test:
  imports:
    - lifelib
  commands:
    - pip check
    - lifelib-create --help
  requires:
    - pip

about:
  home: https://lifelib.io
  summary: Actuarial models in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
