{% set name = "lifelib" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lifelib-{{ version }}.tar.gz
  sha256: b78dc488f9b82ebe8fa03807fbc49cb3f1658e96dfba3919ce997e4fffb0780d

build:
  entry_points:
    - lifelib-create = lifelib.commands.create:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - modelx >=0.12.1
    - python >=3.6

test:
  imports:
    - lifelib
  commands:
    - pip check
    - lifelib-create --help
  requires:
    - pip

about:
  home: https://lifelib.io
  summary: Actuarial models in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
