{% set name = "lifelib" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lifelib-{{ version }}.tar.gz
  sha256: cf44e816ec0f28d39d55aaf96c95d051d7bf4c6a8d26deae718f036010d34aaf

build:
  entry_points:
    - lifelib-create = lifelib.commands.create:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - modelx >=0.12.1
    - python >={{ python_min }}

test:
  imports:
    - lifelib
  commands:
    - pip check
    - lifelib-create --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://lifelib.io
  summary: Actuarial models in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
